export const correspondentesData = [
  {
    cidade: "Maricá",
    nome: "Em definição",
    bio: "Cultura, comércio tradicional, festas e histórias locais.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Saquarema",
    nome: "Em definição",
    bio: "Cultura, turismo, eventos e identidade da cidade.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Araruama",
    nome: "Em definição",
    bio: "Histórias, personagens locais e economia da cidade.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Iguaba Grande",
    nome: "Em definição",
    bio: "Cobertura cultural e valorização do comércio local.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "São Pedro da Aldeia",
    nome: "Em definição",
    bio: "Tradição, cultura e projetos comunitários.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Arraial do Cabo",
    nome: "Em definição",
    bio: "Turismo, cultura, eventos e identidade cabista.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Cabo Frio",
    nome: "Em definição",
    bio: "Cobertura cultural e comercial com foco positivo.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Búzios",
    nome: "Em definição",
    bio: "Experiências locais, cultura, turismo e comércio.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Rio das Ostras",
    nome: "Em definição",
    bio: "Cultura, eventos e histórias da cidade.",
    instagram: "",
    status: "em_formacao",
  },
];

