export const correspondentesData = [
  {
    cidade: "Maricá",
    nome: "Em definição",
    bio: "Correspondente Cultural Classilagos em Maricá.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Saquarema",
    nome: "Em definição",
    bio: "Correspondente Cultural Classilagos em Saquarema.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Araruama",
    nome: "Em definição",
    bio: "Correspondente Cultural Classilagos em Araruama.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Iguaba Grande",
    nome: "Em definição",
    bio: "Correspondente Cultural Classilagos em Iguaba Grande.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "São Pedro da Aldeia",
    nome: "Em definição",
    bio: "Correspondente Cultural Classilagos em São Pedro da Aldeia.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Arraial do Cabo",
    nome: "Em definição",
    bio: "Correspondente Cultural Classilagos em Arraial do Cabo.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Cabo Frio",
    nome: "Em definição",
    bio: "Correspondente Cultural Classilagos em Cabo Frio.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Búzios",
    nome: "Em definição",
    bio: "Correspondente Cultural Classilagos em Búzios.",
    instagram: "",
    status: "em_formacao",
  },
  {
    cidade: "Rio das Ostras",
    nome: "Em definição",
    bio: "Correspondente Cultural Classilagos em Rio das Ostras.",
    instagram: "",
    status: "em_formacao",
  },
];
