const POSTAIS = [
  // ============= MARICÁ =============
  {
    id: "marica-01",
    cidade: "Maricá",
    titulo: "Maricá – cartão 01",
    caminho: "/postais/marica/marica-01.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "marica-02",
    cidade: "Maricá",
    titulo: "Maricá – cartão 02",
    caminho: "/postais/marica/marica-02.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "marica-03",
    cidade: "Maricá",
    titulo: "Maricá – cartão 03",
    caminho: "/postais/marica/marica-03.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "marica-04",
    cidade: "Maricá",
    titulo: "Maricá – cartão 04",
    caminho: "/postais/marica/marica-04.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "marica-05",
    cidade: "Maricá",
    titulo: "Maricá – cartão 05",
    caminho: "/postais/marica/marica-05.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "marica-06",
    cidade: "Maricá",
    titulo: "Maricá – cartão 06",
    caminho: "/postais/marica/marica-06.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "marica-07",
    cidade: "Maricá",
    titulo: "Maricá – cartão 07",
    caminho: "/postais/marica/marica-07.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "marica-08",
    cidade: "Maricá",
    titulo: "Maricá – cartão 08",
    caminho: "/postais/marica/marica-08.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "marica-09",
    cidade: "Maricá",
    titulo: "Maricá – cartão 09",
    caminho: "/postais/marica/marica-09.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "marica-10",
    cidade: "Maricá",
    titulo: "Maricá – cartão 10",
    caminho: "/postais/marica/marica-10.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "marica-11",
    cidade: "Maricá",
    titulo: "Maricá – cartão 11",
    caminho: "/postais/marica/marica-11.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "marica-12",
    cidade: "Maricá",
    titulo: "Maricá – cartão 12",
    caminho: "/postais/marica/marica-12.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },

  // ============= SAQUAREMA =============
  {
    id: "saquarema-01",
    cidade: "Saquarema",
    titulo: "Saquarema – cartão 01",
    caminho: "/postais/saquarema/saquarema-01.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "saquarema-02",
    cidade: "Saquarema",
    titulo: "Saquarema – cartão 02",
    caminho: "/postais/saquarema/saquarema-02.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "saquarema-03",
    cidade: "Saquarema",
    titulo: "Saquarema – cartão 03",
    caminho: "/postais/saquarema/saquarema-03.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "saquarema-04",
    cidade: "Saquarema",
    titulo: "Saquarema – cartão 04",
    caminho: "/postais/saquarema/saquarema-04.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "saquarema-05",
    cidade: "Saquarema",
    titulo: "Saquarema – cartão 05",
    caminho: "/postais/saquarema/saquarema-05.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "saquarema-06",
    cidade: "Saquarema",
    titulo: "Saquarema – cartão 06",
    caminho: "/postais/saquarema/saquarema-06.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "saquarema-07",
    cidade: "Saquarema",
    titulo: "Saquarema – cartão 07",
    caminho: "/postais/saquarema/saquarema-07.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "saquarema-08",
    cidade: "Saquarema",
    titulo: "Saquarema – cartão 08",
    caminho: "/postais/saquarema/saquarema-08.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "saquarema-09",
    cidade: "Saquarema",
    titulo: "Saquarema – cartão 09",
    caminho: "/postais/saquarema/saquarema-09.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "saquarema-10",
    cidade: "Saquarema",
    titulo: "Saquarema – cartão 10",
    caminho: "/postais/saquarema/saquarema-10.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "saquarema-11",
    cidade: "Saquarema",
    titulo: "Saquarema – cartão 11",
    caminho: "/postais/saquarema/saquarema-11.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "saquarema-12",
    cidade: "Saquarema",
    titulo: "Saquarema – cartão 12",
    caminho: "/postais/saquarema/saquarema-12.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },

  // ============= BÚZIOS =============
  {
    id: "buzios-01",
    cidade: "Búzios",
    titulo: "Búzios – cartão 01",
    caminho: "/postais/buzios/buzios-01.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "buzios-02",
    cidade: "Búzios",
    titulo: "Búzios – cartão 02",
    caminho: "/postais/buzios/buzios-02.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "buzios-03",
    cidade: "Búzios",
    titulo: "Búzios – cartão 03",
    caminho: "/postais/buzios/buzios-03.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "buzios-04",
    cidade: "Búzios",
    titulo: "Búzios – cartão 04",
    caminho: "/postais/buzios/buzios-04.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "buzios-05",
    cidade: "Búzios",
    titulo: "Búzios – cartão 05",
    caminho: "/postais/buzios/buzios-05.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "buzios-06",
    cidade: "Búzios",
    titulo: "Búzios – cartão 06",
    caminho: "/postais/buzios/buzios-06.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "buzios-07",
    cidade: "Búzios",
    titulo: "Búzios – cartão 07",
    caminho: "/postais/buzios/buzios-07.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "buzios-08",
    cidade: "Búzios",
    titulo: "Búzios – cartão 08",
    caminho: "/postais/buzios/buzios-08.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "buzios-09",
    cidade: "Búzios",
    titulo: "Búzios – cartão 09",
    caminho: "/postais/buzios/buzios-09.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "buzios-10",
    cidade: "Búzios",
    titulo: "Búzios – cartão 10",
    caminho: "/postais/buzios/buzios-10.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "buzios-11",
    cidade: "Búzios",
    titulo: "Búzios – cartão 11",
    caminho: "/postais/buzios/buzios-11.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "buzios-12",
    cidade: "Búzios",
    titulo: "Búzios – cartão 12",
    caminho: "/postais/buzios/buzios-12.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },

  // ============= ARRAIAL DO CABO =============
  {
    id: "arraial-01",
    cidade: "Arraial do Cabo",
    titulo: "Arraial do Cabo – cartão 01",
    caminho: "/postais/arraial/arraial-01.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "arraial-02",
    cidade: "Arraial do Cabo",
    titulo: "Arraial do Cabo – cartão 02",
    caminho: "/postais/arraial/arraial-02.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "arraial-03",
    cidade: "Arraial do Cabo",
    titulo: "Arraial do Cabo – cartão 03",
    caminho: "/postais/arraial/arraial-03.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "arraial-04",
    cidade: "Arraial do Cabo",
    titulo: "Arraial do Cabo – cartão 04",
    caminho: "/postais/arraial/arraial-04.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "arraial-05",
    cidade: "Arraial do Cabo",
    titulo: "Arraial do Cabo – cartão 05",
    caminho: "/postais/arraial/arraial-05.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "arraial-06",
    cidade: "Arraial do Cabo",
    titulo: "Arraial do Cabo – cartão 06",
    caminho: "/postais/arraial/arraial-06.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "arraial-07",
    cidade: "Arraial do Cabo",
    titulo: "Arraial do Cabo – cartão 07",
    caminho: "/postais/arraial/arraial-07.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "arraial-08",
    cidade: "Arraial do Cabo",
    titulo: "Arraial do Cabo – cartão 08",
    caminho: "/postais/arraial/arraial-08.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "arraial-09",
    cidade: "Arraial do Cabo",
    titulo: "Arraial do Cabo – cartão 09",
    caminho: "/postais/arraial/arraial-09.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "arraial-10",
    cidade: "Arraial do Cabo",
    titulo: "Arraial do Cabo – cartão 10",
    caminho: "/postais/arraial/arraial-10.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "arraial-11",
    cidade: "Arraial do Cabo",
    titulo: "Arraial do Cabo – cartão 11",
    caminho: "/postais/arraial/arraial-11.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
  {
    id: "arraial-12",
    cidade: "Arraial do Cabo",
    titulo: "Arraial do Cabo – cartão 12",
    caminho: "/postais/arraial/arraial-12.webp",
    credito: "Foto: Carlinhos Soares / Classilagos",
    descricao: "",
  },
];

